# basic options
title: Xunyi Wang
email: xunyiwan@buffalo.edu
github_username: xunyiwang
description: 302 Jacobs Management Center. Buffalo, NY 14260-4000

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
