# basic options
title: 302 Jacobs Management Center. Buffalo, NY 14260-4000
contact information: 
email: xunyiwan@buffalo.edu
github_username: xunyiwan

# Build settings
markdown: kramdown
theme: minima
