# basic options
google_analytics: UA-101614443-1

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site
title: Xunyi Wang (王训一)
email: xunyiwan@buffalo.edu
github_username: xunyiwang
description: 302 Jacobs Management Center. Buffalo, NY 14260-4000

# Build settings
markdown: kramdown
theme: minima

