# basic options
title: xunyi's blog
author: xunyi
email: xunyiwan@buffalo.edu
description: a self-described website
twitter_username: none
github_username:  xunyiwan

# Build settings
markdown: kramdown
theme: minima
