# basic options
title: Xunyi Wang
contact information: 302 Jacobs Management Center. Buffalo, NY 14260-4000
email: xunyiwan@buffalo.edu
description: a self-described website
github_username:  xunyiwan

# Build settings
markdown: kramdown
theme: minima
